/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_JniFuncMain */

#ifndef _Included_com_study_jnilearn_JniFuncMain
#define _Included_com_study_jnilearn_JniFuncMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_JniFuncMain
 * Method:    createJniObject
 * Signature: ()Lcom/study/jnilearn/JniTest;
 */
JNIEXPORT jobject JNICALL Java_com_study_jnilearn_JniFuncMain_createJniObject
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
